declare module 'lucide-react' {
  import { FC, SVGProps } from 'react';
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
  }
  export type Icon = FC<IconProps>;
  export const AlertTriangle: Icon;
  export const Check: Icon;
  export const ChevronDown: Icon;
  export const ChevronUp: Icon;
  export const Download: Icon;
  export const Eye: Icon;
  export const Image: Icon;
  export const ImageIcon: Icon;
  export const LogOut: Icon;
  export const Moon: Icon;
  export const Play: Icon;
  export const Search: Icon;
  export const Settings: Icon;
  export const Share2: Icon;
  export const Star: Icon;
  export const Sun: Icon;
  export const Trash2: Icon;
  export const Upload: Icon;
  export const X: Icon;
  export const Zap: Icon;
  export const List: Icon;
  export const Heart: Icon;
  export const Plus: Icon;
  export const Minus: Icon;
  export const Info: Icon;
  export const Edit2: Icon;
  export const ThumbsUp: Icon;
  export const Loader2: Icon;
  export const Layers: Icon;
  export const DownloadCloud: Icon;
  export const SlidersHorizontal: Icon;
  export const ArrowDownAZ: Icon;
  export const CloudUpload: Icon;
  export const ArrowRightLeft: Icon;
  export const Menu: Icon;
  export const ChevronFirst: Icon;
  export const ChevronLeft: Icon;
  export const ChevronRight: Icon;
  export const ChevronLast: Icon;
  export const HelpCircle: Icon;
  export const FileSpreadsheet: Icon;
  export const Circle: Icon;
  export const CheckCircle2: Icon;
  export const ExternalLink: Icon;
  export const Film: Icon;
  export const Clock: Icon;
  export const History: Icon;
  export const ShoppingBag: Icon;
}
